# Generated by Django 2.0 on 2017-12-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.RenameModel('ModelSites', 'ModelSite')

    ]
