# Generated by Django 2.0 on 2017-12-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0002_auto_20171222_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=2048, unique=True)),
                ('person_id', models.ForeignKey(on_delete=None, to='admin_interface.ModelPerson')),
            ],
        ),
        migrations.AlterField(
            model_name='modelsite',
            name='name',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
