# Generated by Django 2.0 on 2017-12-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0003_auto_20171222_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelkeyword',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.ModelPerson'),
        ),
    ]
